create database scm
use scm

CREATE TABLE supply_chain_data (
	`Product type` VARCHAR(9) NOT NULL, 
	`SKU` VARCHAR(5) NOT NULL, 
	`Price` DECIMAL(38, 0) NOT NULL, 
	`Availability(%)` DECIMAL(38, 0) NOT NULL, 
	`Number of products sold` DECIMAL(38, 0) NOT NULL, 
	`Revenue generated` DECIMAL(38, 0) NOT NULL, 
	`Customer demographics` VARCHAR(10) NOT NULL, 
	`Stock levels` DECIMAL(38, 0) NOT NULL, 
	`Lead times(Days)` DECIMAL(38, 0) NOT NULL, 
	`Order quantities` DECIMAL(38, 0) NOT NULL, 
	`Shipping times(Days)` DECIMAL(38, 0) NOT NULL, 
	`Shipping carriers` VARCHAR(9) NOT NULL, 
	`Shipping costs` DECIMAL(38, 0) NOT NULL, 
	`Supplier name` VARCHAR(10) NOT NULL, 
	`Location` VARCHAR(9) NOT NULL, 
	`Manufacturing lead time (Days)` DECIMAL(38, 0) NOT NULL, 
	`Production volumes(Units/Week)` DECIMAL(38, 0) NOT NULL, 
	`Manufacturing lead time` DECIMAL(38, 0) NOT NULL, 
	`Manufacturing costs` DECIMAL(38, 0) NOT NULL, 
	`Inspection results` VARCHAR(7) NOT NULL, 
	`Defect rates` DECIMAL(38, 2) NOT NULL, 
	`Transportation modes` VARCHAR(4) NOT NULL, 
	`Routes` VARCHAR(7) NOT NULL, 
	`Costs` DECIMAL(38, 0) NOT NULL
);

load data infile
"E:\supply_chain_data.csv"
into table supply_chain_data
fields terminated by ','
enclosed by '"'
lines terminated by '\n'
ignore 1 rows ;

select * from supply_chain_data

## 1. What is the total Revenue Generated by the cosmetics that are used by male customers only ?

select `Product type` , `Customer demographics` , `Revenue generated` , sum(`Revenue generated`) as `Total Revenue Generated` from supply_chain_data 
where `Customer demographics` = 'Male' and `Product type` = 'cosmetics'

# 2. Find the stock level of the Hair care Product in Banglore and shipped by carrier B ?

select `Product type`, `Stock levels` , `Location` , `Shipping carriers`  from supply_chain_data 
where `Product type` = 'Haircare' and `Location` = 'Bangalore' and `Shipping carriers` = 'Carrier B'

# 3. What is the total number of skin care product available in chennai ?

select `Product type`,`Location`, count(`Product type`) as `Number of Products` from supply_chain_data 
where  `Product type`= 'skincare' and `Location`= 'Chennai'

# 4. What will be the total price of available skin care products in Delhi   ?

select `Product type` , `Location` , sum(`Price`) as `Total price` from supply_chain_data 
where `Product type` = 'skincare' and `Location` = 'Delhi'

# 5. How much quantity of hair care products required to supplier 3 of Mumbai to meet the order quantity ?

select `Product type` , `Location` , `Supplier name` , `Order quantities` from supply_chain_data
where `Location` = 'Mumbai' and `Supplier name` = 'Supplier 3' and `Product type` = 'haircare'

# 6. What is the total number of hair care Products Available in Mumbai ?

select `Product type`,`Location`, count(`Product type`) as `Number of Products` from supply_chain_data 
where  `Product type`= 'haircare' and `Location`= 'Mumbai'

# 7. How much time carrier C of kolkata suppliers 2 will take to shipp all the hair care products ?

select `Product type`,`Location` , `Supplier name` , `Shipping carriers`, `Shipping times(Days)` from supply_chain_data 
where `Supplier name` = 'Supplier 2' and `Location`= 'Kolkata' and `Shipping carriers` = 'Carrier C' and `Product type` = 'haircare'

# 8. Which type of Consumer Consumes Most number of skin care products and Find the number of skin care products used by them ?

select `Product type` , `Customer demographics`, count(`Customer demographics`) as `Consumption of Products` from supply_chain_data
where `Product type`= 'skincare' group by `Customer demographics`


select `Product type` , `Customer demographics`, count(`Customer demographics`) as `Consumption of Products` from supply_chain_data
where `Product type`= 'skincare' group by `Customer demographics` limit 1

# 9. Which product Produces the lowest Revenue that are only Transported by Road in Route A anb b ?

select `Product type`,`Revenue generated`,`Transportation modes`,`Routes`from supply_chain_data 
where `Transportation modes` = 'Road' and `Routes` in ('Route A','Route B')
order by `Revenue generated` asc limit 2


# 10. Find the suppliers that transports most number of cosmetics that is used by female customers only ?

select `Product type`,count(`Product type`) as `Number of Products`,`Customer demographics`,`Supplier name` , `Transportation modes` from supply_chain_data
where `Customer demographics`= 'Female' and `Product type` = 'cosmetics'


